import { AppConfig, AppLogic, ListItem } from "global.slint";
import { FormPanel } from "components/form-panel.slint";
import { ItemPanel } from "components/item-panel.slint";
import { VerticalBox } from "std-widgets.slint";

export { AppConfig, AppLogic, ListItem}

export component AppWindow inherits Window {
    title: "Список справ";
    icon: @image-url("../assets/checkbox.png");
    min-width: 480px;
    max-width: 600px;
    background: AppConfig.color_primary.darker(90%);
    VerticalBox {
        ItemPanel { }
        FormPanel { }
    }
}