export struct ListItem {
    completed: bool,
    description: string,
    datetime: string,
}

export global AppConfig {
    out property <color> color_primary: #907AD6;
    out property <color> color_secondary: #CDE5D7;
    out property <color> color_tertiary: #75abe6;
    in property <string> data_path: ".todo.dat";
    out property <length> font-size: 14px;
    in-out property <[ListItem]> list_items: [];
}

export global AppLogic {
    callback load_list_items();
    callback dump_list_items();
    callback pop_list_item(int) -> ListItem;
    callback put_list_item(int, ListItem);
    callback edit_list_item(int, ListItem);
    callback export_list_items();
    callback import_list_items();
}